### ISSUE TITLE
Restock LV 303 issue

### ISSUE THREAD

**Issue by zorg2044** [KSP-RO/RealPlume-StockConfigs#114]
https://i.imgur.com/I33Cv70.png

**Comment by woeller** [comment]
Thanks in advance!

**Comment by zorg2044** [comment]
@woeller should be fixed in the dev branch now :) 896ec0fa6a29fd81cf30ae2672143bbeb39e3ffd

Not sure when I will be able to cut a new release though, there are some updates I want to work on and there have been some bugs spotted in smokescreen 2.8.9
