### ISSUE TITLE
Mainsail Plume issue when using Restock

### ISSUE THREAD

**Issue by woeller** [KSP-RO/RealPlume-StockConfigs#118]
Apparently, when using Restocks Mainsail, the effects of the Stock version are also used.

![screenshot27](https://user-images.githubusercontent.com/35576383/80810602-82a62980-8bc4-11ea-8b3f-ee6e1849012b.png)

**Comment by woeller** [comment]
Same with the Skipper.

![screenshot28](https://user-images.githubusercontent.com/35576383/80811050-6787e980-8bc5-11ea-9f0c-fc954304ce63.png)

**Comment by zorg2044** [comment]
@woeller I've fixed the mainsail in dev, the skipper looks fine to me? The stock skipper gets a kerolox plume and the restock one gets a cryogenic one 

(1. becuase its inspired by the LE7 and 2. because CryoEngines provides an optional LH2 config for it)
