### ISSUE TITLE
Using ModuleManager's in-game config reload removes SRBs from game.

### ISSUE THREAD

**Issue by coyotesfrontier** [KSP-RO/RealPlume-StockConfigs#119]
This is a really odd issue and I've never seen anything like it before, but reloading Module Manager's config cache appears to completely wipe SRBs from the game. Restarting the game fixes this, but not being able to use the reload is quite annoying. Tested with no other mods then the latest RealPlume-Stock, RealPlume, and SmokeScreen.

[ConfigCacheAfterReload.txt](https://github.com/KSP-RO/RealPlume-StockConfigs/files/4569307/ConfigCacheAfterReload.txt)

[ConfigShaAfterReload.txt](https://github.com/KSP-RO/RealPlume-StockConfigs/files/4569308/ConfigShaAfterReload.txt)

[ConfigCacheBeforeReload.txt](https://github.com/KSP-RO/RealPlume-StockConfigs/files/4569309/ConfigCacheBeforeReload.txt)

[ConfigShaBeforeReload.txt](https://github.com/KSP-RO/RealPlume-StockConfigs/files/4569310/ConfigShaBeforeReload.txt)

[KSP.log](https://github.com/KSP-RO/RealPlume-StockConfigs/files/4569311/KSP.log)

**Comment by zorg2044** [comment]
if someone can figure out why and if it indeed is a realplume issue (and not MM itself) and there is an easy fix Im happy to implement it but otherwise i am not particularly inclined to go chasing after such an esoteric bug. I havent the faintest clue where to start.
