### ISSUE TITLE
Shrimp SRB no plume

### ISSUE THREAD

**Issue by majorPhysics** [KSP-RO/RealPlume-StockConfigs#123]
The shrimp srb is marked in the configs to not load if waterfall is present. Waterfall doesn't have configs for the shrimp srb, so this should be reversed.

**Comment by zorg2044** [comment]
Thanks, fixed now https://github.com/KSP-RO/RealPlume-StockConfigs/commit/9dc1b50119959f9bab1e8de9482c99523695c21a
