### ISSUE TITLE
RealFuels Stockalike Conflict

### ISSUE THREAD

**Issue by Maeyanie** [KSP-RO/RealPlume-StockConfigs#13]
When these configs are used together with RealFuels Stockalike engines, they overwrite the ModuleEnginesRF it uses with ModuleEnginesFX.
This breaks limited ignitions, ullage, and some other advanced features.

**Comment by LebedevRI** [comment]
This is already being tracked in https://github.com/NathanKell/ModularFuelSystem/issues/98

**Comment by Maeyanie** [comment]
Yes, that does look like the same issue. Though it's filed on the wrong thing. Closing this one.
