### ISSUE TITLE
SETIprobeParts

### ISSUE THREAD

**Issue by Y3mo** [KSP-RO/RealPlume-StockConfigs#57]
Hey,
SETIprobeParts rescales some stock engines for early probe variety and I was wondering how to make configs for them. http://spacedock.info/mod/848

Specifially the stock 2.5m poodle "liquidEngine2-2" is resized to 0.625m and given the new name "setiLFOenginePomeranian".
And the stock 1.25m RT-10 SRB "solidBooster" is resized to 0.625m and named "setiMiniSRB3".

There are also a couple of RCS thruster parts, but I guess RealPlume/SmokeScreen does not need special configs for that?

Best regards,
Y3mo

**Comment by Nhawks1717** [comment]
You can check out the wiki page regarding how to add support for engines [here](https://github.com/KSP-RO/RealPlume/wiki/Adding-a-Plume-to-an-Engine)
