### ISSUE TITLE
v1.0.0 Release Update

### ISSUE THREAD

**Issue by Nhawks1717** [KSP-RO/RealPlume-StockConfigs#64]
<p align="center"><img src="https://i.imgur.com/QlcChne.png" width="32" height="32" align="center"/> - Completed <img src="https://i.imgur.com/PHLwu4d.png" width="32" height="32" align="center"/> - In Progress <img src="https://i.imgur.com/hkcIrSN.png" width="32" height="32" align="center"/> - Not Started</p>

<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Stock configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update AB Launchers configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - <s>Update AIES configs</s> **NO LONGER BEING MAINTAINED**
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Atomic Age configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update BahamutoD configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - <s>Update BTSM configs</s> **NO LONGER BEING MAINTAINED**
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Cormorant Aeronology configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Cryo Engines configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update CTN configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - <s>Update Custom Clusters configs</s> **NO LONGER BEING MAINTAINED**
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Direct LV configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Eve Engines configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update FASA configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Home Grown Rockets configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Jool Direct configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Kerbal Stock Launcher Overhaul configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update KOSMOS configs
<img src="https://i.imgur.com/PHLwu4d.png" width="16" height="16" align="center"/> - Update KSO configs **NEED 1.3 UPDATE**
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update KSPX configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update KW Community Fixes configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update KW Rocketry configs
<img src="https://i.imgur.com/PHLwu4d.png" width="16" height="16" align="center"/> - Update Moar Mk1 configs **NEED 1.3 UPDATE**
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Modular Rocket Systems configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Near Future Spacecraft configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update New Tantares configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update New Tantares LV configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Part Overhauls configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Planetary Base Inc configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Procedural Parts configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Real Scale Boosters configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update RLA Stockalike configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update RN Cygnus configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - <s>Update RS Capsuldedyne configs</s> **NO LONGER BEING MAINTAINED**
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Sum Dum Heavy Industries configs
<img src="https://i.imgur.com/PHLwu4d.png" width="16" height="16" align="center"/> - Update Space Launch System configs **NEED 1.3 UPDATE**
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - <s>Update Space Shuttle configs</s> **NO LONGER BEING MAINTAINED**
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update SpaceY configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update SpaceY Expanded configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update SXT configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Taerobee configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Tantares configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Tantares LV configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Tundra Exploration configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update Ven's Stock Revamp configs
<img src="https://i.imgur.com/QlcChne.png" width="16" height="16" align="center"/> - Update VX Series II configs
<img src="https://i.imgur.com/PHLwu4d.png" width="16" height="16" align="center"/> - Update Wiki
<img src="https://i.imgur.com/PHLwu4d.png" width="16" height="16" align="center"/> - Update Forum Thread

**Comment by DerpyFirework** [comment]
Just going to let you know, I'm going to be working with Beale, the dev of Tantares and TantaresLV, to add the NewTantares and TantaresLV configs directly to the mods downloads, so I'll also be removing them from this repo.

**Comment by Nhawks1717** [comment]
Awesome, thanks for the heads up

**Comment by Vladimir-csp** [comment]
Any chance there would be RCS plume configs?

BTW, this setup works great for the new NFSpacefraft engines:
```
@PART[orbital-engine-0625]:FOR[RealPlume]:NEEDS[SmokeScreen]
{
    PLUME
    {
        name = Hypergolic-OMS-Red         //pre-fabbed plume you want
        transformName = thrustTransform //which transform to attach the plume
        localRotation = 0,0,0           //Optional - Any rotation needed
        localPosition = 0,0,0.4           //Any offset needed
        fixedScale = 0.4                  //Size adjustment to resize to engine
        energy = 1                      //Adjust length of plume
        speed = 1                       //Adjust speed to fit resize, 
                                        //generally close to 1:1 with scale.
    }
	
    @MODULE[ModuleEngines*]
    {
        @name = ModuleEnginesFX
        %powerEffectName = Hypergolic-OMS-Red
    }
}

@PART[orbital-engine-25]:FOR[RealPlume]:NEEDS[SmokeScreen]
{
    PLUME
    {
        name = Hypergolic-OMS-Red         //pre-fabbed plume you want
        transformName = thrustTransform //which transform to attach the plume
        localRotation = 0,0,0           //Optional - Any rotation needed
        localPosition = 0,0,0.4		//Any offset needed
        fixedScale = 0.4              //Size adjustment to resize to engine
        energy = 1                      //Adjust length of plume
        speed = 1                       //Adjust speed to fit resize, 
                                        //generally close to 1:1 with scale.
    }

    @MODULE[ModuleEngines*]
    {
        @name = ModuleEnginesFX
        %powerEffectName = Hypergolic-OMS-Red
    }
}


@PART[orbital-engine-125]:FOR[RealPlume]:NEEDS[SmokeScreen]
{
    PLUME
    {
        name = Hypergolic-OMS-Red         //pre-fabbed plume you want
        transformName = thrustTransform //which transform to attach the plume
        localRotation = 0,0,0           //Optional - Any rotation needed
        localPosition = 0,0,0           //Any offset needed
        fixedScale = 1                  //Size adjustment to resize to engine
        energy = 1                      //Adjust length of plume
        speed = 1                       //Adjust speed to fit resize, 
                                        //generally close to 1:1 with scale.
    }
    @MODULE[ModuleEngines*]
    {
        @name = ModuleEnginesFX
        %powerEffectName = Hypergolic-OMS-Red
    }
}

@PART[orbital-engine-375]:FOR[RealPlume]:NEEDS[SmokeScreen]
{
    PLUME
    {
        name = Hypergolic-OMS-Red         //pre-fabbed plume you want
        transformName = thrustTransform //which transform to attach the plume
        localRotation = 0,0,0           //Optional - Any rotation needed
        localPosition = 0,0,0           //Any offset needed
        fixedScale = 1                  //Size adjustment to resize to engine
        energy = 1                      //Adjust length of plume
        speed = 1                       //Adjust speed to fit resize, 
                                        //generally close to 1:1 with scale.
    }
    @MODULE[ModuleEngines*]
    {
        @name = ModuleEnginesFX
        %powerEffectName = Hypergolic-OMS-Red
    }
}
```

**Comment by PhineasFreak** [comment]
@Vladimir-csp Do note that having a "ModuleEnginesFX" definition inside the ModuleEngine patcher is now invalid. RPS handles that internally.

**Comment by Nhawks1717** [comment]
I'll look into those configs when I start working on this again. Hit a block with motivation for it :P
