### ISSUE TITLE
Curly braces in configs

### ISSUE THREAD

**Issue by AccidentalDisassembly** [KSP-RO/RealPlume-StockConfigs#66]
(Copypasta from forum):

Missing curly braces:
RealPlume-Stock\AIES\microEngineSE1.cfg
RealPlume-Stock\Space Launch System\RS-25.cfg

Unusual quote marks:
RealPlume-Stock\DIRECT_LV\DirectSRBX.cfg
RealPlume-Stock\DIRECT_LV\DIRECT_RS25.cfg
RealPlume-Stock\Tantares\Phoenix_Ex_Engine_A.cfg

**Comment by Nhawks1717** [comment]
Fixed in 1.0.0
