### ISSUE TITLE
Incorrect capitalization of GameData in latest release

### ISSUE THREAD

**Issue by aeTIos** [KSP-RO/RealPlume-StockConfigs#67]
As title. The ZIP has a folder 'Gamedata'. Please be kind to users on case-sensitive filesystems and rename that to 'GameData'. Thanks :D

**Comment by Nhawks1717** [comment]
Will do. I'll make sure to include this in the next update! I'm going to leave this open until I update so I don't forget.

**Comment by Nhawks1717** [comment]
Fixed in 1.0.0
