### ISSUE TITLE
Mulitple MM passes specified on a few patches

### ISSUE THREAD

**Issue by blowfishpro** [KSP-RO/RealPlume-StockConfigs#69]
In `RealPlume/RealPlume-Stock/SXT Continued/SXTnuclearramjet.cfg`:
`@PART[SXTnuclearramjet]:FOR[RealPlume]:AFTER[SXT]`

In `RealPlume/RealPlume-Stock/Taerobee/Aerobee_Jr.cfg`:
`@PART[taerobee_aerobee]:FOR[RealPlume]:FINAL`

In `RealPlume/RealPlume-Stock/Taerobee/Little_Leo.cfg`:
`@PART[taerobee_TinyTim]:FOR[RealPlume]:FINAL`

**Comment by blowfishpro** [comment]
Patches can't be both `:FOR[RealPlume]` and `:AFTER[SXT]` or `:FOR[RealPlume]` and `:FINAL`, they need only one pass specifier

**Comment by blowfishpro** [comment]
This will probably be an error in the next version of ModuleManager

**Comment by Nhawks1717** [comment]
Interesting, thanks for the info. Probably explains why the Taerobee configs weren't overwriting the plumes packaged with the mod. I'll take a look at this when I can and update it!

**Comment by PhineasFreak** [comment]
@Nhawks1717 If it helps, you can also specify a **!PLUME,*{}** node inside the part plume pass. That way you can define your own without having to worry about correctly patching the existing ones.

**Comment by blowfishpro** [comment]
Should have checked on this before MM was released, but I forgot.  The PR above should fix it though
