### ISSUE TITLE
No Plume or Sound with USI Sounding Rockets

### ISSUE THREAD

**Issue by fwdixon** [KSP-RO/RealPlume-StockConfigs#75]
The USI Sounding Rockets configs aren't working. No plume or sound is generated.

**Comment by fwdixon** [comment]
My simple fix didn't work, so I made a small temporary config file that works until I can figure out all the SmokeScreen functions in the original. I posted the link in the forum thread.

**Comment by zorg2044** [comment]
Seems to have been fixed by Nhawks in v1.3.1

https://github.com/KSP-RO/RealPlume-StockConfigs/wiki/Changelog
