### ISSUE TITLE
SXT: update name of Mun Lander

### ISSUE THREAD

**Issue by ncanceill** [KSP-RO/RealPlume-StockConfigs#83]
**Description**
The config for the SXT Mun Lander is incorrectly applied to the stock Mun Lander (which does not even have an engine).

**Root cause**
The SXT Mun Lander was renamed from `MEMLander` to `MEMLanderSXT` because it conflicted with the stock `MEMLander` from Making History. Specifically [RealPlume-Stock/SXT Continued/MEMLander.cfg](https://github.com/KSP-RO/RealPlume-StockConfigs/blob/master/GameData/RealPlume-Stock/SXT%20Continued/MEMLander.cfg#L1) has the problem.

**Fix**
Obvious: replace `MEMLander` with `MEMLanderSXT` in the file mentioned herebefore. Optionally, rename the file accordingly.

**Additional information**
See issue [#70](https://github.com/linuxgurugamer/SXTContinued/issues/70) and commit [5ffd417](https://github.com/linuxgurugamer/SXTContinued/commit/5ffd4177f07a1e8ab723c53f2e60b83893547d10) in SXT.

**Comment by ncanceill** [comment]
I just saw [this announcement](https://forum.kerbalspaceprogram.com/index.php?/topic/130576-161-realplume-stock-v131-11419-better-late-than-never-update/page/40/&tab=comments#comment-3339961) so I suppose this is not getting solved anytime soon

I will post this on the forum so others may benefit

**Comment by zorg2044** [comment]
@ncanceill Looking at that issue I guess its been fixed on the SXT side?

**Comment by zorg2044** [comment]
Misunderstood, I guess what was fixed was the other patches. RealPlume name is fixed now to ``MEMLanderSXT``

Commit: https://github.com/KSP-RO/RealPlume-StockConfigs/commit/9230c59683f8df1347adfb3147c09460dd662086
