### ISSUE TITLE
KerbalAtomics Eel engine plume too high

### ISSUE THREAD

**Issue by GHrynk** [KSP-RO/RealPlume-StockConfigs#84]
The plume position for the Eel 0.625m NTR in the KerbalAtomics patch appears to be placed too high.  More details, and suggested fix, on forum here:
https://forum.kerbalspaceprogram.com/index.php?/topic/130576-161-realplume-stock-v131-11419-better-late-than-never-update/&do=findComment&comment=3641911

**Comment by zorg2044** [comment]
![Screenshot 2019-09-05 12 41 37](https://user-images.githubusercontent.com/39182212/64322025-2eb65700-cfdb-11e9-82ed-a0f52cb410fc.png)

Looks like the config was written with the engine bell not deployed. Fixed now in the development branch and will be available next release.
