### ISSUE TITLE
Issue with Interstellar Extended - Plasma Thruster 

### ISSUE THREAD

**Issue by nansuchao** [KSP-RO/RealPlume-StockConfigs#9]
Hello, in the last few days I'm trying to create a specific config in RealPlume for Interstellar Extended.
There's one engine, the Plasma Thruster, that doesn't show the realplume effect, careless of what I can do. 
Here's the cfg for RealPlume: http://pastebin.com/9MVrwkZZ
Here's the MM cache regarding the engine: http://pastebin.com/S6YDwD0E
It seems ok, but in game I still have the stock plume.

Another little issue with the Magnetic Nozzle: http://pastebin.com/PkWjshKX
When you activate the engine in game, the plume doesn't show at all. BUT, if you open the Smoke Screen GUI, you can activate the plume/flare just clicking on Single Emit Timer. I can't find the reason for that.

Here's the MM Cache of the Magnetic Nozzle: http://pastebin.com/q2G4hyd6

**Comment by Felger** [comment]
Interesting, he's got a weird naming scheme, but I suppose it has to do with the custom engine mechanics used in KSPI.  I'd suggest different plume appearances, personally.  I might go through at some point and rebuild effects specifically for those engines.  The exhaust velocities have to be absurd, which makes for a **very** different plume appearance.  (The magnetic nozzle you linked is expelling exhaust at a whopping 353km/s, where the best ion engines we've ever built and tested on the ground in real life have exhaust velocities on the order of 20-50km/s.)

Anyway, things to try:
For the Plasma Thruster, try this:
```
@PART[InterstellarPlasmaThrusterUpgraded]:FOR[RealPlume]:NEEDS[SmokeScreen] //Quantum Vacuum Plasma Thruster
{
    PLUME
    {
        name = Hydynelox-A7
        transformName = TT
        localRotation = 0,0,0
        localPosition = 0,0,1
        fixedScale = 4
        energy = 1
        speed = 1
    }
    @MODULE[ModuleEngines*]
    {
        @name = ModuleEngineFX
        !runningEffectName = DELETE
        %powerEffectname = Hydynelox-A7
    }
}
```
Also make sure the `@MODULE[ModuleEngines*]` isn't modifying some custom engine config used by KSPI

On which note, for the Magnetic Nozzle:
```
@PART[TweakableMagneticNozzle]:FOR[RealPlume]:NEEDS[SmokeScreen] //Magnetic Nozzle
{
    PLUME
    {
        name = Hydrolox-Lower
        transformName = thrustTransform
        plumePosition = 0,0,-0.5 
        plumeScale = 3
        energy = 20
        speed = 5
        flarePosition = 0,0,1.5
        flareScale = 2
      }
    @MODULE[ WarpModuleEnginesFX]
    {
        !runningEffectName = DELETE
        %powerEffectName = Hydrolox-Lower
    }
}
```
Odds are if the engine module on the original part has `FX` on the end of it, it's compatible with SmokeScreen already, no changes needed.  Also, you had a few of the parameters misnamed, corrected those for ya.

Give those a shot and let me know how it goes!

**Comment by nansuchao** [comment]
No changes about the Plasma Thruster, while the Magnetic Nozzle has the same a weird behavior. for example, in orbit, I need to use the Smoke Screen Power to make the flare show.

![screenshot537](https://cloud.githubusercontent.com/assets/14057077/9583493/90f348da-5003-11e5-8d73-1743e15a3339.png)

Note that there's a typo in the Magnetic Nozzle cfg, it should be
@MODULE[WarpModuleEnginesFX]

About the parameters misnamed, I tried to indicate two different speed and energy for flare/plume

**Comment by Felger** [comment]
>About the parameters misnamed, I tried to indicate two different speed and energy for flare/plume
That's not a supported feature at this point, and I'm not sure I ever will, since the flare's purpose is to live in the engine bell, it shouldn't need any speed or energy adjustments.

For the Plasma Thruster, can you post the original part config (before RealPlume modifies it)? Perhaps a clue can be found there.  In fact, for both it might be useful.

**Comment by nansuchao** [comment]
Sure, here's the Plasma Thruster: http://pastebin.com/vMjR39Th

Magnetic Nozzle: http://pastebin.com/5FnLNvgE

I tried to differentiate plume from flare for aesthetic reason, and for better match the uncommon bell/nozzle of those engines.

**Comment by sswelm** [comment]
Actualy the theoretical exit velocity of Fission Frament Engine (Magnetic Noozle + Dusty Plasma) would be 5170 km/s (source: http://www.nasa.gov/pdf/718391main_Werka_2011_PhI_FFRE.pdf)

**Comment by ABZB** [comment]
in the realplumes node, replace 'transformName = ...'
with:

transformName = #$/../MODULE[ModuleEngines*]/thrustVectorTransformName$

this way, it copies whatever the proper transform name is, and you don't have to worry about the proper transform name yourself. Also, this makes it easier to adapt it for other engines with the same engine module (such as the ones from my patches).

**Comment by nansuchao** [comment]
This way Module Manager is giving me an error during loading

**Comment by ABZB** [comment]
odd. I just tried it myself, I got exactly 1 error:

[LOG 13:33:57.286] [ModuleManager] Applying node RealPlume/000_Generic_Plumes/actualtransformname/@PART[*]:HAS[@PLUME[*]]:FOR[zRealPlume] to WarpPlugin/Parts/Engines/MagneticNozzle/MagneticNoozle/TweakableMagneticNozzle
[LOG 13:33:57.287] [ModuleManager] Error - Cannot parse variable search when replacing (%) key transformName = #$/../MODULE[ModuleEngines*]/thrustVectorTransformName$

this is happening due to the following realplumes file:
GameData\RealPlume\000_Generic_Plumes
which contains:

@PART[*]:HAS[@PLUME[*]]:FOR[zRealPlume]:NEEDS[SmokeScreen]:FINAL
{
    @PLUME,*
    {
        %transformName = #$/../MODULE[ModuleEngines*]/thrustVectorTransformName$
    }
}

apparently, realplumes already does what I said by itself. however, the magnetic nozzle has modulename:

WarpModuleEnginesFX

so the '*' at the end isn't getting it.
try editing it (that file) to *ModuleEngines*
it can't find the thrustVectorTransformName b/c

**Comment by nansuchao** [comment]
Tried, no changes...

**Comment by ABZB** [comment]
hmmm

**Comment by Felger** [comment]
All righty, so I've got it figured out.  Looking at the original format, it looks like it's expecting a particular set of effect names which aren't called out anywhere in any other node (which is awesome).

For the Magnetoplasmadynamic thruster:
```
EFFECTS
{
  electric_qvp
  {
  }
  electric_red
  {
  }
  electric_argon
  {
  }
  electric_xenon
  {
  }
  electric_hydrogen
  {
  }
  electric_ammonia
  {
  }
}
```
So to use RealPlume plumes with these, we're going to need to do some custom configs.  I'll have to talk to Sarbian about if it's possible to change a node title like that... I doubt it, which means custom configs.  Not too hard, just a little time consuming.

For the Magnetic nozzle, it wouldn't surprise me to see the same thing happen, where it needs the name `running_closed` to work properly, which isn't currently supported by RealPlume. 

Finally, as of now, SmokeScreen doesn't adjust particle size or position based on TweakScale parameters, so any resizing of the engine won't adjust the plume (unless I missed an update to SmokeScreen where Sarbian put in some magic).

**Comment by nansuchao** [comment]
Good to know, thanks for helping. Can I leave the issue open for further developement?

**Comment by Felger** [comment]
Absolutely, at some point in the near-ish future I plan to go in and build out some new plumes, some of the ones we have already aren't as awesome as they could be, so I'll be making improvements.  I'll try and roll in some of these effects, or make a way to change the effect name in the config so you can use it for this role.

**Comment by nansuchao** [comment]
Thanks, if I can and if you want, I'll help with pleasure.

**Comment by sswelm** [comment]
Notice in the last update of KSPI I downgraded the PlasmaThruster to regular Graphic. Hopefully this will allow you to create better RealPlume Support

**Comment by nansuchao** [comment]
Sadly, for the moment no...
