### ISSUE TITLE
SSTU support

### ISSUE THREAD

**Issue by zorg2044** [KSP-RO/RealPlume-StockConfigs#99]

**Comment by KerbalKore** [comment]
SSTU already has native RealPlume support, but with the legacy plumes. 
![image](https://user-images.githubusercontent.com/51207379/64877936-4018e800-d607-11e9-9e6a-576846c0fefa.png)

**Comment by zorg2044** [comment]
Huh. There was a comment on the thread implying it wasn't supported. I hadnt actually gotten round to looking into the SSTU files proper. Closing this issue. Thanks.
